# .docker/docker-compose.ci.yml
version: '3.8'

services:
    nginx:
        extends:
            file: docker-compose.yml
            service: nginx

    php:
        extends:
            file: docker-compose.yml
            service: php

    mysql:
        extends:
            file: docker-compose.yml
            service: mysql

    mailer:
        extends:
            file: docker-compose.yml
            service: mailer
