volumes:
    mysql-data:

services:
    mysql:
        image: mysql:8.0
        env_file:
          - .env
        ports:
            - ${MYSQL_PORT}:3306
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        volumes:
            - mysql-data:/var/lib/mysql
        healthcheck:
            test: ["CMD-SHELL", "mysqladmin -u root -p$$MYSQL_ROOT_PASSWORD ping -h mysql || exit 1"]
            start_period: 10s
            interval: 2s
            timeout: 5s
            retries: 20
