volumes:
  mysql-data:

services:
  nginx:
    build:
      context: nginx
      args:
        SERVER_NAME: ${SERVER_NAME}
    restart: always
    ports:
      - ${NGINX_HTTP_PORT}:80
    volumes:
      - ../public:/app/public:default
    depends_on:
      - php
  php:
    # Removed container_name to allow scaling of php-worker service
    build:
      context: php
      args:
        XDEBUG_CLIENT_HOST: ${PHP_XDEBUG_CLIENT_HOST}
        XDEBUG_CLIENT_PORT: ${PHP_XDEBUG_CLIENT_PORT}
        XDEBUG_START_WITH_REQUEST: ${PHP_XDEBUG_START_WITH_REQUEST}
        XDEBUG_MODE: ${PHP_XDEBUG_MODE}
    restart: always
    working_dir: /app
    env_file:
      - .env
    environment:
      PHP_IDE_CONFIG: serverName=${SERVER_NAME}
    volumes:
      - ../:/app
    depends_on:
      - mysql
  mysql:
    container_name: bookstore_mysql
    image: mysql
    restart: always
    ports:
      - ${MYSQL_PORT}:3306
    volumes:
      - ../.docker/mysql-data:/var/lib/mysql:rw
    user: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
  mailer:
      container_name: bookstore_mailer
      image: axllent/mailpit
      restart: always
      ports:
          - "1025"
          - "8025"
      environment:
          MP_SMTP_AUTH_ACCEPT_ANY: 1
          MP_SMTP_AUTH_ALLOW_INSECURE: 1
  php-worker-contact-form:
      scale: 1
      extends:
          service: php
      command: php bin/console messenger:consume contactForm --time-limit=3600
